/*
 * 扩展接入
 *
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2003 struct for InlineResponse2003
type InlineResponse2003 struct {
	// -1代表错误 1代表成功 0代表提示
	State string `json:"state"`
	// 状态码对应的详细信息
	Msg string `json:"msg"`
	// 验证码图片ID
	Virifycodeid string `json:"virifycodeid"`
	// 验证码图片数据data:image/png;base64,格式
	Virifyimage string `json:"virifyimage"`
}
