/*
 * 扩展接入
 *
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse200Nfts struct for InlineResponse200Nfts
type InlineResponse200Nfts struct {
	// NFT的id
	Id string `json:"id,omitempty"`
	// NFT的数量
	Amount string `json:"amount,omitempty"`
}
