/*
 * 扩展接入
 *
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	Contract string `json:"contract"`
	Account string `json:"account"`
	// 用户持有的查询合约的所有NFT
	Nfts []InlineResponse200Nfts `json:"nfts"`
}
