/*
 * 扩展接入
 *
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	// 0代表失败  1代表成功
	State string `json:"state"`
	// state=0时为错误信息，state=1时交易hash
	Hash string `json:"hash"`
	// 合约地址
	Contract string `json:"contract"`
	// 源地址
	Form string `json:"form"`
	// 目的地址
	To string `json:"to"`
	// NFT的ID
	Id string `json:"id"`
	// 转移的数量
	Amount string `json:"amount"`
}
