/*
 * 扩展接入
 *
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject2 struct for InlineObject2
type InlineObject2 struct {
	// 手机号
	Phone string `json:"phone"`
	// 图片验证码ID
	Robotcodeid string `json:"robotcodeid"`
	// 图片验证码识别结果
	Robotcode string `json:"robotcode"`
}
