/*
 * 扩展接入
 *
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject3 struct for InlineObject3
type InlineObject3 struct {
	// 该函数传“”空字符串
	Phone string `json:"phone"`
}
